ALTER TABLE "claims" ADD COLUMN IF NOT EXISTS "roofSquares" DOUBLE PRECISION;
ALTER TABLE "claims" ADD COLUMN IF NOT EXISTS "wasteFactorPct" DOUBLE PRECISION;
ALTER TABLE "claims" ADD COLUMN IF NOT EXISTS "pitch" TEXT;
ALTER TABLE "claims" ADD COLUMN IF NOT EXISTS "storyCount" INTEGER;
ALTER TABLE "claims" ADD COLUMN IF NOT EXISTS "supplementOpportunities" JSONB NOT NULL DEFAULT '[]';
