import { prisma } from "@/server/db/client";

/**
 * Who should OWN a deal generated by `actorUserId`?
 * A canvasser assigned to a sales rep funnels everything to that rep — so their
 * knocks, leads, and appointments auto-assign to (and become visible by) the rep.
 * Anyone else owns their own work.
 */
export async function resolveOwningRepId(companyId: string, actorUserId: string): Promise<string> {
  const u = await prisma.user.findFirst({
    where: { id: actorUserId, companyId },
    select: { role: true, salesRepId: true },
  });
  if (u?.role === "canvasser" && u.salesRepId) return u.salesRepId;
  return actorUserId;
}
