"use client";

import * as React from "react";
import { auditLabel, type ProposalCertificate } from "@/lib/proposal-signature";

/**
 * The certificate of electronic signature — the sheet behind the proposal.
 *
 * WHY IT EXISTS. A signature drawn onto a page proves very little on its own;
 * what makes an electronic signature stand up under ESIGN and UETA is the
 * RECORD around it — that the signer agreed to transact electronically before
 * they signed, when each step happened, from what address, and that the
 * document has not moved since. Every e-signature product a lender has ever
 * accepted attaches a page like this, and it is the page their file reviewer
 * looks for.
 *
 * PRINT ONLY. It is not part of the sales document and no homeowner reading
 * their proposal on a phone wants a table of IP addresses in the middle of it.
 * It lands on the sheet after the colophon, which means it is in the filed PDF
 * — the copy that goes to the lender — and in anything the customer prints for
 * themselves.
 *
 * The FINGERPRINT is the part that does the work a signature image cannot: the
 * document the customer saw is a frozen snapshot and nothing is recomputed from
 * it, so a hash of that snapshot is a hash of what was signed. Re-run it and a
 * altered PDF is answerable without trusting the PDF.
 */
export function SignatureCertificate({ certificate }: { certificate: ProposalCertificate }) {
  const { signature } = certificate;

  return (
    <section
      data-certificate
      // Hidden on screen; the print stylesheet turns it into a sheet of its own.
      className="hidden bg-white text-neutral-900"
    >
      <div className="mx-auto w-full max-w-3xl">
        <header className="flex items-baseline justify-between gap-6 border-b-2 border-neutral-900 pb-3">
          <h2 className="font-display text-2xl font-semibold tracking-[-0.01em]">
            Certificate of electronic signature
          </h2>
          <span className="text-[10px] font-semibold uppercase tracking-[0.18em] text-neutral-500">
            {certificate.companyName}
          </span>
        </header>

        <p className="mt-4 max-w-[92ch] text-[11px] leading-relaxed text-neutral-600">
          This certificate records the electronic signing of the document named below. It is
          generated by the system that presented the document and is issued under the Electronic
          Signatures in Global and National Commerce Act (ESIGN) and the Uniform Electronic
          Transactions Act (UETA), which give an electronic signature the same legal effect as a
          handwritten one where the signer has consented to transact electronically.
        </p>

        {/* ── what was signed ─────────────────────────────────────────────── */}
        <Group title="The document">
          <Row label="Document">{certificate.documentTitle}</Row>
          <Row label="Customer">{certificate.customerName}</Row>
          {certificate.propertyAddress && <Row label="Property">{certificate.propertyAddress}</Row>}
          <Row label="Fingerprint (SHA-256)">
            <span className="break-all font-mono text-[10px] leading-relaxed">
              {certificate.fingerprint}
            </span>
          </Row>
        </Group>

        {/* ── who signed it ───────────────────────────────────────────────── */}
        <Group title="The signer">
          <Row label="Name">{signature.name || "—"}</Row>
          {signature.email && <Row label="Delivered to">{signature.email}</Row>}
          <Row label="Signature">
            {signature.method === "drawn"
              ? "Drawn by hand on a touchscreen or pointer"
              : signature.method === "typed"
                ? "Adopted from the signer's typed name"
                : "Not captured"}
          </Row>
          <Row label="Signed">
            {signature.via === "in_person"
              ? signature.hostName
                ? `In person, on a device provided by ${signature.hostName}`
                : "In person, on a representative's device"
              : "Remotely, from the signer's own proposal link"}
          </Row>
          <Row label="Consent to sign electronically">
            {signature.consentAt
              ? `Given ${fullStamp(signature.consentAt)}, before the signature was applied`
              : "Not recorded"}
          </Row>
          {certificate.ip && <Row label="IP address">{certificate.ip}</Row>}
          {certificate.userAgent && (
            <Row label="Device">
              <span className="break-all text-[10px] leading-relaxed">{certificate.userAgent}</span>
            </Row>
          )}
        </Group>

        {/* ── the trail ───────────────────────────────────────────────────── */}
        <div data-cert-group className="mt-6">
          <h3 className="text-[10px] font-semibold uppercase tracking-[0.18em] text-neutral-500">
            Document history
          </h3>
          <table className="mt-2 w-full border-collapse text-[11px]">
            <thead>
              <tr className="border-b border-neutral-300 text-left text-[9px] uppercase tracking-[0.14em] text-neutral-500">
                <th className="py-1.5 pr-3 font-semibold">Event</th>
                <th className="py-1.5 pr-3 font-semibold">When</th>
                <th className="py-1.5 pr-3 font-semibold">By</th>
                <th className="py-1.5 font-semibold">From</th>
              </tr>
            </thead>
            <tbody>
              {certificate.events.map((e, i) => (
                <tr key={`${e.type}-${e.at}-${i}`} className="border-b border-neutral-200">
                  <td className="py-1.5 pr-3 font-medium">
                    {auditLabel(e.type)}
                    {e.detail && <span className="font-normal text-neutral-500"> — {e.detail}</span>}
                  </td>
                  <td className="whitespace-nowrap py-1.5 pr-3 tabular-nums">{fullStamp(e.at)}</td>
                  <td className="py-1.5 pr-3">{e.actor ?? "—"}</td>
                  <td className="py-1.5 tabular-nums">{e.ip ?? "—"}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <p className="mt-6 border-t border-neutral-300 pt-3 text-[10px] leading-relaxed text-neutral-500">
          Times are shown in the time zone of the device that produced this certificate. The
          document history is append-only and is not editable from within the application.
        </p>
      </div>
    </section>
  );
}

/** A timestamp written out in full — a certificate is read, not skimmed. */
function fullStamp(iso: string): string {
  const d = new Date(iso);
  return `${d.toLocaleDateString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
  })} ${d.toLocaleTimeString(undefined, { hour: "numeric", minute: "2-digit", second: "2-digit" })}`;
}

function Group({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div data-cert-group className="mt-5">
      <h3 className="text-[10px] font-semibold uppercase tracking-[0.18em] text-neutral-500">
        {title}
      </h3>
      <dl className="mt-2 divide-y divide-neutral-200 border-y border-neutral-200">{children}</dl>
    </div>
  );
}

function Row({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="grid grid-cols-[10rem_minmax(0,1fr)] gap-4 py-1.5">
      <dt className="text-[11px] text-neutral-500">{label}</dt>
      <dd className="text-[11px] font-medium text-neutral-900">{children}</dd>
    </div>
  );
}
